/*
 * JanelaPrincipal.java
 *
 * Created on October 26, 2008, 11:47 AM
 */

package piscemu.views;

/**
 *
 * @author  davivercillo
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /** Creates new form JanelaPrincipal */
    public JanelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        menuConfigurar = new javax.swing.JMenu();
        itemCarregar = new javax.swing.JMenuItem();
        itemReiniciar = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        menuExecutar = new javax.swing.JMenu();
        itemMicroinstrucao = new javax.swing.JMenuItem();
        itemInstrucao = new javax.swing.JMenuItem();
        itemTodas = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemTutorial = new javax.swing.JMenuItem();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practical Instruction Set Computer Simulator (PISCSim)");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("janelaPrincipal"); // NOI18N
        setResizable(false);

        menuConfigurar.setMnemonic('c');
        menuConfigurar.setText("Configurar");

        itemCarregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemCarregar.setMnemonic('a');
        itemCarregar.setText("Carregar arquivo");
        menuConfigurar.add(itemCarregar);

        itemReiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemReiniciar.setMnemonic('r');
        itemReiniciar.setText("Reiniciar");
        menuConfigurar.add(itemReiniciar);

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSair.setMnemonic('s');
        itemSair.setText("Sair");
        menuConfigurar.add(itemSair);

        menuPrincipal.add(menuConfigurar);

        menuExecutar.setMnemonic('e');
        menuExecutar.setText("Executar");

        itemMicroinstrucao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        itemMicroinstrucao.setMnemonic('m');
        itemMicroinstrucao.setText("Próxima microinstrução");
        menuExecutar.add(itemMicroinstrucao);

        itemInstrucao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemInstrucao.setMnemonic('i');
        itemInstrucao.setText("Próxima instrução");
        menuExecutar.add(itemInstrucao);

        itemTodas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemTodas.setMnemonic('t');
        itemTodas.setText("Todas instruções");
        menuExecutar.add(itemTodas);

        menuPrincipal.add(menuExecutar);

        menuAjuda.setMnemonic('a');
        menuAjuda.setText("Ajuda");

        itemTutorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemTutorial.setMnemonic('u');
        itemTutorial.setText("Tutorial");
        menuAjuda.add(itemTutorial);

        itemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        itemSobre.setMnemonic('b');
        itemSobre.setText("Sobre");
        menuAjuda.add(itemSobre);

        menuPrincipal.add(menuAjuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCarregar;
    private javax.swing.JMenuItem itemInstrucao;
    private javax.swing.JMenuItem itemMicroinstrucao;
    private javax.swing.JMenuItem itemReiniciar;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuItem itemTodas;
    private javax.swing.JMenuItem itemTutorial;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuConfigurar;
    private javax.swing.JMenu menuExecutar;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables

}
